# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rujcar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for rujcar
  pod 'AFNetworking', '~> 3.2.1'

  target 'rujcarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'rujcarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
